### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [bonwalton/Dasmoto2#7]
Grade: Meets expectations

Summary:
Nice job on this first project! I love your use of `<div>` elements to wrap the different sections of your page, your organized HTML, your use of descriptive `alt` attributes on your `<img>` elements, and your use of the `html` selector in the CSS.

A couple things to work on here: 1. using relative file paths for your CSS and image files and 2. making sure your elements are closed correctly.

Next, as a stretch goal, I challenge you to research and implement media queries to make your page responsive for all screen widths. This is a challenge I think you are ready for based on your work with this project! Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by bonwalton** [comment]
Thanks for your review and your helpful suggestions, @aubreywullschleger!
